# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source
COPY . .

# Build project
RUN npm run build

# Production image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built files and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm install --production --ignore-scripts

# Set entrypoint
ENTRYPOINT ["node", "dist/index.js"]
